### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by f00d4tehg0dz** [jacbz/Lofi#13]
I'm unsure why I'm getting this error when trying to run the Lofi docker image. 

```
[[ATraceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/app.py", line 15, in <module>
    limiter = Limiter(
TypeError: __init__() got multiple values for argument 'key_func'
```

The commands I used in Docker are as follows. Using your Dockerfile

1) `docker build -t lofi .`

2) `docker run -p 8080:5000 -v /Lofi/model:/model -v /Lofi/server:/server lofi`

**Comment by zachOS-tech** [comment]
@f00d4tehg0dz Did you resolve this issue on your end? I'm getting the same error you did when I try to use the docker commands you used.

**Comment by f00d4tehg0dz** [comment]
> @f00d4tehg0dz Did you resolve this issue on your end? I'm getting the same error you did when I try to use the docker commands you used.
So it took me awhile to figure it out. I had to place model and checkpoints folder inside server. So for example 
`/Lofi/server/model/`

and then commands I ran

`docker run -it -p 8080:5000 -v /Lofi/server/:/lofi --name lofigen`
`docker build -t lofi .`

**Comment by f00d4tehg0dz** [comment]
> @f00d4tehg0dz Did you resolve this issue on your end? I'm getting the same error you did when I try to use the docker commands you used.

i posted the docker here: if that helps you: https://hub.docker.com/repository/docker/f00d4tehg0dz/lofi/general
